version: "3.8"

services:
  mockcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 2000:3000

    environment:
      - DATABASE_URL=postgresql://sampleuser:sample@db:5432/MockData

    depends_on: 
      - db
    networks:
      - sampleNetwork
    
  db:
    image: postgres:alpine3.19
    environment: 
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: MockData
      POSTGRES_USER: sampleuser
    volumes:
      - test:/var/lib/postgresql/data
    networks:
      - sampleNetwork


  pg_admin:
    image: dpage/pgadmin4:8
    depends_on: 
      - db
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=noobielearner04@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root

volumes:
  test:

networks:
  sampleNetwork:
